
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example.compscript.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ROOT = 14;
  public static final int CHAR = 7;
  public static final int SINGLE_LINE_COMMENT = 2;
  public static final int DIVISION = 12;
  public static final int END = 16;
  public static final int ERROR = 17;
  public static final int MODULO = 15;
  public static final int BOOLEAN = 6;
  public static final int STRING = 8;
  public static final int WHOLE = 4;
  public static final int EOF = 0;
  public static final int MULTIPLICATION = 10;
  public static final int error = 1;
  public static final int SUBSTRACTION = 11;
  public static final int BLOCK_COMMENT = 3;
  public static final int ADDITION = 9;
  public static final int POWER = 13;
  public static final int DOUBLE = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SINGLE_LINE_COMMENT",
  "BLOCK_COMMENT",
  "WHOLE",
  "DOUBLE",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "ADDITION",
  "MULTIPLICATION",
  "SUBSTRACTION",
  "DIVISION",
  "POWER",
  "ROOT",
  "MODULO",
  "END",
  "ERROR"
  };
}

